module Public.Consts.TextGeneral (bossDefeated,helpFlag1,helpFlag2,helpFlag3, wantRest, restDanger, restNormal, restSafe, levelUp1, levelUp2, continue, idleOptionsOne,idleOptionsTwo,pressEnter,exitGame,enterName,moveSymbols,moveOptions,moveIllegal,healMessage,outOfHeal,playerDeath1,playerDeath2,playerDeath3,playerDeath4) where
-- General text

pressEnter = "Welcome! press enter to start!"
enterName = "Please enter a name for our Hero!:"
idleOptionsOne = "What do you want to do "
idleOptionsTwo = "\n\tMove (m)\n\tRest (r)\n\tQuit (q)"
exitGame = "Are you sure you want to quit?\nAll progress will be lost (y/n): "
playerDeath1 = " has died...\n"
playerDeath2 = " gathered: "
playerDeath3 = " coins,\nand got to layer: "
playerDeath4 = ".\nBetter luck next time!"
moveSymbols = "Moved path & Walls: | - +\nStarting position: S\nPlayer: P"
moveOptions = "Where do you want to walk? (w = up, a = left, s = down, d = right, q = stop moving):"
moveIllegal = "Illegal direction."
healMessage = "You have healed for "
outOfHeal = "You are out of healing potions!"
continue = "Press enter to continue..."
levelUp1 = "You have leveled up, "
levelUp2 = "! MAXHP increased.\nDo you want to;\n(s) Sharpen your sword,\n(a) Strengthen your armour?"
restSafe = "You feel safe here..."
restNormal = "There isn't anyone around..."
restDanger = "You feel as if you are being watched..."
wantRest = "\nDo you want to rest? (y/n):"
bossDefeated = " has defeated Oddvar Brå. Thus the world is free from his reign of terror.\nNo longer will people have to remember what they were doing on that fatefull day...\n"


helpFlag1 = "Welcome to my PROG2006 project program.\nThe game is a simple Rougelike where you fight monsters, level up and advance the dungeon.\nYour goal is to fight your way to the bottom, and discover who awaits at the depths (layer 100).\n"
helpFlag2 = "All the controls are presented ingame and should be pretty self explanatory, even for inexpirienced players.\nYou gain EXP from killing monsters and advancing layers. When you level up you can upgrade your weapon or increase your armour.\n"
helpFlag3 = "On the map you can encounter monsters, merchants and loot rooms.\n"