name:                hashlite-prog2006-project
version:             0.1.0.0
github:              "AxelJacobsen/hashlite-prog2006-project"
license:             BSD3
author:              "Axel Jacobsen"
maintainer:          "aejacobs@stud.ntnu.no"
copyright:           "Copyright (c) 2022 Axel E. W. Jacobsen"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/AxelJacobsen/hashlite#readme>

dependencies:
- base >= 4.7 && < 5
- random
- directory

library:
  source-dirs: src

executables:
  hashlite-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashlite-prog2006-project

tests:
  hashlite-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hashlite-prog2006-project
    - QuickCheck
    - HUnit
